

orig = ['Unnamed: 0',
         'Title of the contribution in original language',
         'Current publication status > Date',
         'Subtitle of the contribution in original language',
         'Type',
         'Workflow > Step',
         'Original language',
         'Electronic version(s) of this work > DOI (Digital Object Identifier)[1]',
         'Organisations > Organisational unit[1]',
         'Organisations > Organisational unit[2]',
         'Organisations > Organisational unit[3]',
         'Organisations > Organisational unit[4]',
         'Organisations > Organisational unit[5]',
         'Organisations > Organisational unit[6]',
         'Organisations > Organisational unit[7]',
         'Organisations > Organisational unit[8]',
         'Organisations > Organisational unit[9]',
         'Organisations > Organisational unit[10]',
         'Journal > Journal[1]:Titles',
         'Journal > Journal[1]:ISSNs',
         'UUID',
         'DOI',
         'orig_doi',
         'upw_doi',
         'upw_doi_lowercase',
         'upw_error',
         'upw_error_message',
         'upw_free_fulltext_url',
         'upw_is_boai_license',
         'upw_is_free_to_read',
         'upw_is_subscription_journal',
         'upw_license',
         'upw_oa_color_x',
         'upw_oa_color_verbose',
         'ff',
         'ff_provided_organization_string',
         'ff_match',
         'ff_score',
         'ff_terms',
         'ff_message',
         'ff_match_subgroup',
         'DOI_isnull',
         'pub_uuid',
         'pure_year']

new = ['Unnamed: 0',
 'Title of the contribution in original language',
 'Current publication status > Date',
 'Subtitle of the contribution in original language',
 'Type',
 'Workflow > Step',
 'Original language',
 'Electronic version(s) of this work > DOI (Digital Object Identifier)[1]',
 'Organisations > Organisational unit[1]',
 'Organisations > Organisational unit[2]',
 'Organisations > Organisational unit[3]',
 'Organisations > Organisational unit[4]',
 'Organisations > Organisational unit[5]',
 'Organisations > Organisational unit[6]',
 'Organisations > Organisational unit[7]',
 'Organisations > Organisational unit[8]',
 'Organisations > Organisational unit[9]',
 'Organisations > Organisational unit[10]',
 'Journal > Journal[1]:Titles',
 'Journal > Journal[1]:ISSNs',
 'UUID',
 'DOI',
 'orig_doi',
 'own_doi_lowercase',
 'upw_doi',
 'upw_doi_lowercase',
 'upw_error',
 'upw_error_message',
 'upw_free_fulltext_url',
 'upw_is_boai_license',
 'upw_is_free_to_read',
 'upw_is_subscription_journal',
 'upw_license',
 'upw_oa_color_x',
 'upw_oa_color_verbose',
 'ff',
 'ff_provided_organization_string',
 'ff_match',
 'ff_score',
 'ff_terms',
 'ff_message',
 'ff_match_subgroup',
 'DOI_isnull',
 'pub_uuid',
 'pure_year']

print(orig == new)
